site_name: Elysia API
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Getting Started: index.md
  - Basic Usage: basic.md
  - Advanced Usage: advanced_usage.md
  - Preprocessing: preprocess.md
  - Customising Elysia:
    - Overview: Customising/index.md
    - Technical Overview: Customising/technical_overview.md
    - Tool Construction: Customising/creating_your_own_tools.md
    - Custom Objects: Customising/custom_objects.md
    - Environment: Customising/environment.md
  - API: 
    - Overview: API/index.md
    - Client Management: API/client_management.md
    - User Management: API/user_management.md
    - Routes: API/routes.md
    - Payload Formats: API/payload_formats.md
 
  - Examples:
    # - Intermediate: Examples/02_intermediate.md
    - Sentiment Analysis: Examples/sentiment_analysis.md
    - Fantasy Adventure: Examples/fantasy_adventure.md
  - Reference:
    - Preprocessor: Reference/Preprocessor.md
    - Tree: Reference/Tree.md
    - WeaviateClient: Reference/Client.md
    # - Configure: Reference/Configure.md
    - Objects: Reference/Objects.md
    # - Tools: Reference/Tools.md
    - Result: Reference/Result.md

plugins:
  - social
  - search
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/weaviate/elysia
    - icon: fontawesome/brands/github
      link: https://github.com/weaviate/elysia-frontend
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dannyjameswilliams
    - icon: fontawesome/brands/github-alt
      link: https://github.com/thomashacker
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dannyjameswilliams/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/edwardschmuhl/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences 
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg