discovered_tools:
  retrieval:
    Query:
      class_name: Query
      name: query
      description: Query the knowledge base via semantic/keyword search
      end: false
      available: true
    Aggregate:
      class_name: Aggregate
      name: aggregate
      description: Aggregate information by performing operations on the knowledge base
      end: false
      available: true
  text:
    CitedSummarizer:
      class_name: CitedSummarizer
      name: cited_summarizer
      description: Summarize information with citations
      end: true
      available: true
    FakeTextResponse:
      class_name: FakeTextResponse
      name: text_response
      description: Generate a text response to the user
      end: true
      available: true
  visualization:
    BasicLinearRegression:
      class_name: BasicLinearRegression
      name: basic_linear_regression
      description: Perform basic linear regression analysis
      end: false
      available: true
    Visualise:
      class_name: Visualise
      name: visualise
      description: Create visualizations of data
      end: false
      available: true
  postprocessing:
    SummariseItems:
      class_name: SummariseItems
      name: summarise_items
      description: Summarise retrieved items from query results
      end: false
      available: true
  mcp:
    # MCP tools will be dynamically added here when mcp.json is configured
    # Example:
    # MCP_example_server:
    #   class_name: MCP_example_server
    #   name: mcp_example_server
    #   description: MCP server 'example_server' - provides access to multiple tools
    #   end: false
    #   available: true
  other: {}

